name: Root

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build...
        run: pnpm build

      - name: Log in to the Container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $REGISTRY -u $ --password-stdin

      - name: Build Docker image
        run: docker build -t $REGISTRY/$IMAGE:stage .

      - name: Push docker image
        run: docker push $REGISTRY/$IMAGE:stage

      - name: Deploy webhook
        run: ls -lah